name: otp
version: 0.1.0
author: Yulian Kuncheff <yulian@kuncheff.com>
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  test: any
  crypto: "<=0.10.0"
  base32: any
