name: otp
version: 0.1.0
author: Yulian Kuncheff <yulian@kuncheff.com>
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  unittest: ">=0.9.0 < 0.10.0"
  crypto: ">=0.9.0 < 0.10.0"
  base32: ">=0.1.1"
