name: otp
version: 3.0.0-nullsafety.0
description: RFC6238 Time-Based One-Time Password / Google Authenticator Library
homepage: https://github.com/Daegalus/dart-otp
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  base32: ^2.0.0-nullsafety
  crypto: "^3.0.0-nullsafety"
  logging: "^1.0.0-nullsafety"
dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
dependency_overrides:
 crypto:
    git:
      url: https://github.com/dart-lang/crypto.git
      ref: "master"
 logging: ^1.0.0-nullsafety